#!/bin/bash

#Se puede modificar en xargs las siguientes opciones:
#-P: indica el numero de cores que se van a usar
#-L: indica el numero de imagenes que procesa cada core en cada instancia


find . -name "*.png" -print0 | xargs -0 -P10 -L4 optipng -o7

echo "########################################## Ahora toca la parte de pngquant #################################"

find . -name "*.png" -print0 | xargs -0 -P10 -L4 pngquant -f --skip-if-larger --ext .png --quality 0-64 --speed 1 --strip --verbose
